/**
 * Language mapping helper for theme and UI translations
 */

export const LANGUAGE_MAP: Record<string, string> = {
  pt: "Portuguese",
  es: "Spanish",
  fr: "French",
  de: "German",
  it: "Italian",
  ja: "Japanese",
  ko: "Korean",
  zh: "Chinese",
  ru: "Russian",
  ar: "Arabic",
  hi: "Hindi",
  tr: "Turkish",
  nl: "Dutch",
  sv: "Swedish",
  pl: "Polish",
  vi: "Vietnamese",
  th: "Thai",
  id: "Indonesian",
  uk: "Ukrainian",
  cs: "Czech",
  hu: "Hungarian",
  ro: "Romanian",
  el: "Greek",
  da: "Danish",
  fi: "Finnish",
  no: "Norwegian",
  he: "Hebrew",
  bg: "Bulgarian",
  hr: "Croatian",
  sk: "Slovak",
  lt: "Lithuanian",
  sl: "Slovenian",
  et: "Estonian",
  lv: "Latvian",
  sr: "Serbian",
  ms: "Malay",
  bn: "Bengali",
  fa: "Persian",
  ur: "Urdu",
  ta: "Tamil",
  te: "Telugu",
  ml: "Malayalam",
  kn: "Kannada",
  mr: "Marathi",
  gu: "Gujarati",
  pa: "Punjabi",
  sw: "Swahili",
  am: "Amharic",
  km: "Khmer",
  lo: "Lao",
  my: "Burmese",
  ne: "Nepali",
  si: "Sinhala",
  ka: "Georgian",
  hy: "Armenian",
  az: "Azerbaijani",
  be: "Belarusian",
  is: "Icelandic",
  mk: "Macedonian",
  mn: "Mongolian",
  cy: "Welsh",
  gl: "Galician",
  eu: "Basque",
  ca: "Catalan",
  af: "Afrikaans",
  zu: "Zulu",
  xh: "Xhosa",
  st: "Sesotho",
  tn: "Tswana",
  yo: "Yoruba",
  ig: "Igbo",
  ha: "Hausa",
  lb: "Luxembourgish",
  mt: "Maltese",
  ga: "Irish",
  gd: "Scottish Gaelic",
  en: "English",
};

/**
 * Gets human-readable language name from language code.
 * @param langCode The language code (e.g., 'pt', 'es')
 * @returns The language name (e.g., 'Portuguese', 'Spanish')
 */
export function getLanguageName(langCode: string): string {
  // eslint-disable-next-line security/detect-object-injection -- lookup by validated lang code
  return LANGUAGE_MAP[langCode] || langCode;
}
