name: Clean All Generated Content

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm deletion of generated content'
        required: true
        default: 'no'
        type: choice
        options:
          - 'no'
          - 'yes'

jobs:
  clean-generated:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Validate confirmation
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "yes" ]; then
            echo "❌ Confirmation not provided. Operation cancelled."
            echo "To proceed, set the 'confirm' input to 'yes'"
            exit 1
          fi
          echo "✅ Confirmation received. Proceeding with cleanup..."
        
      - name: Clean generated content
        run: bun run clean:generated --confirm=yes
        
      - name: Show cleanup results
        run: |
          echo "🧹 Generated content cleanup completed"
          echo "📁 Remaining structure:"
          ls -la docs/ || echo "No docs directory"
          ls -la i18n/*/docusaurus-plugin-content-docs/current/ || echo "No i18n content directories"